apiVersion: dns.gardener.cloud/v1alpha1
kind: DNSEntry
metadata:
  annotations:
    # If you are delegating the DNS management to Gardener, uncomment the following line (see https://gardener.cloud/documentation/guides/administer_shoots/dns_names/)
    #dns.gardener.cloud/class: garden
  name: text
  namespace: default
spec:
  dnsName: "text.ringtest.dev.k8s.ondemand.com"
  ttl: 600
  text:
  - foo
  - "bar bla"
