apiVersion: v1
kind: Service
metadata:
  annotations:
    dns.gardener.cloud/dnsnames: echo.my-dns-domain.com
    dns.gardener.cloud/ttl: "500"
    # If you are delegating the DNS Management to Gardener, uncomment the following line (see https://gardener.cloud/documentation/guides/administer_shoots/dns_names/)
    #dns.gardener.cloud/class: garden

    # expose load balancer with own host name for supporting PROXY protocol (alternative to nip.io suffix)
    # more details here: https://github.com/kubernetes/cloud-provider-openstack/blob/master/docs/openstack-cloud-controller-manager/expose-applications-using-loadbalancer-type-service.md#use-proxy-protocol-to-preserve-client-ip
    loadbalancer.openstack.org/hostname: echo.my-dns-domain.com
    loadbalancer.openstack.org/proxy-protocol: "true"

  name: test-service
  namespace: default
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  sessionAffinity: None
  type: LoadBalancer
